version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.2.0
  maven: circleci/maven@1.4.1

executors:
  docker-openjdk:
    docker:
      - image: cimg/openjdk:21.0.0

jobs:
  build-jar:
    executor: docker-openjdk
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: DEV_AWS_KEY_ID
          aws-region: DEV_AWS_REGION
          aws-secret-access-key: DEV_AWS_SECRET
          profile-name: 619238747039_MerlynCodeArtifactAccess
      - run:
          name: Set CodeArtifact Auth Token as env var for all steps in this job
          command: |
            CODEARTIFACT_AUTH_TOKEN=`./getCodeArtifactAuthToken.sh`
            echo "export CODEARTIFACT_AUTH_TOKEN=${CODEARTIFACT_AUTH_TOKEN}" >> "$BASH_ENV"
      - run:
          name: Build Jar
          command: |
            mvn clean install -DskipTests -Dgpg.skip -s ./settings.xml -f java-does-usb\pom.xml
      - when:
          condition:
            and:
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Publish release
                command: |
                  mvn clean deploy -DskipTests -Dgpg.skip -s ./settings.xml -f java-does-usb/pom.xml

workflows:
  ci:
    jobs:
      - build-jar:
          context:
            - CodeArtifact